# Generated by Django 5.1 on 2024-08-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_messagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmodel',
            old_name='users',
            new_name='user',
        ),
    ]
