# Generated by Django 5.1 on 2024-08-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_rename_users_groupmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.groupmodel'),
        ),
    ]
