# Generated by Django 5.1 on 2024-08-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_messagemodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
