# Generated by Django 5.1 on 2024-08-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumeuser',
            name='color',
            field=models.CharField(default=['slate'], max_length=20),
        ),
    ]
