# Generated by Django 5.1 on 2024-08-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_costumeuser_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumeuser',
            name='color',
            field=models.CharField(choices=[('slate', 'slate'), ('neutral', 'neutral'), ('red', 'red'), ('orange', 'orange'), ('lime', 'lime'), ('green', 'green'), ('teal', 'teal'), ('sky', 'sky'), ('indigo', 'indigo'), ('purple', 'purple'), ('fuchsia', 'fuchsia'), ('pink', 'pink'), ('rose', 'rose')], default='lime', max_length=20),
        ),
    ]
